server:
  port: 8084  # Choose a unique port for Payment Service

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fullstack
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
