server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Fullstack
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka